import { FileText } from 'lucide-react';

const TermsOfService = () => (
  <div className="container" style={{ maxWidth: '800px' }}>
    <div className="card-light">
      <FileText size={48} color="var(--color-orange)" style={{ marginBottom: '24px' }} />
      <h1 style={{ marginBottom: '24px' }}>Terms of Service</h1>
      
      <p style={{ lineHeight: '1.8', opacity: 0.8, marginBottom: '20px' }}>
        Last Updated: May 15, 2026
      </p>

      <h3 style={{ marginTop: '24px', marginBottom: '12px' }}>1. Agreement to Terms</h3>
      <p style={{ lineHeight: '1.8', opacity: 0.8, marginBottom: '16px' }}>
        By accessing SmartAssist, you agree to comply with these Terms of Service. If you do not agree, please discontinue use of our platform.
      </p>

      <h3 style={{ marginTop: '24px', marginBottom: '12px' }}>2. Nature of Service</h3>
      <p style={{ lineHeight: '1.8', opacity: 0.8, marginBottom: '16px' }}>
        SmartAssist is a triage and appointment scheduling assistant. <strong>We do not provide medical diagnosis or treatment.</strong> Our specialist recommendations are generated by an AI assistant and should be used as a guide only. Always consult a qualified medical professional for health concerns.
      </p>

      <h3 style={{ marginTop: '24px', marginBottom: '12px' }}>3. Limitation of Liability</h3>
      <p style={{ lineHeight: '1.8', opacity: 0.8, marginBottom: '16px' }}>
        SmartAssist is not responsible for any direct, indirect, or incidental damages arising from the use or inability to use our services.
      </p>

      <h3 style={{ marginTop: '24px', marginBottom: '12px' }}>4. Emergency Situations</h3>
      <p style={{ lineHeight: '1.8', opacity: 0.8, marginBottom: '16px' }}>
        If you are experiencing a medical emergency, do not use this app. Contact your local emergency services or hospital immediately.
      </p>
    </div>
  </div>
);

export default TermsOfService;
